app/urls.py
from app import views
from django.urls import path
from .views import logout_view

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('hot', views.hot, name="hot"),
    path('question/<int:question_id>/', views.question, name='question'),
    path('new_question/', views.new_question, name='new_question'),
    path('login/', views.login_view, name='login1'),
    path('signup/', views.signup_view, name='signup'),
    path('settings/', views.settings, name='settings'),
    path('tag/<str:tag_name>/', views.questions_by_tag, name='questions_by_tag'),
    path('logout/', logout_view, name='logout'),
]

askme_aandreeva/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import make_password

class SignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Password")
    repeatpassword = forms.CharField(widget=forms.PasswordInput, label="Repeat Password")
    nickname = forms.CharField(max_length=25, label="Nickname")
    avatar = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email is already in use.")
        return email

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        repeatpassword = cleaned_data.get("repeatpassword")
        if password != repeatpassword:
            raise ValidationError("Passwords do not match.")
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.password = make_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(widget=forms.PasswordInput, label='Password')

app/templates/hot.html
{% extends "layouts/base.html"%}
{% load static %}

{% block content %}
    <div class="d-flex align-items-center gap-2 mb-4">
        <h1 class="section-title">Hot Questions</h1>
        <a href="{% url 'index' %}">New Questions</a>
    </div>
    {% for question in questions%}
        {% include 'layouts/question.html' %}
    {% endfor%}
    {% include 'layouts/pagination.html' %}
{% endblock %}

app/templates/index.html
{% extends "layouts/base.html"%}
{% load static %}

{% block content %}
    <div class="d-flex align-items-center gap-2 mb-4">
        <h1 class="section-title">New Questions</h1>
        <a href="{% url 'hot' %}">Hot Questions</a>
    </div>
    {% for question in questions%}  
        {% include 'layouts/question.html' %}
    {% endfor%}
    {% include 'layouts/pagination.html' %}
{% endblock %}

app/templates/login1.html
{% extends "layouts/base.html"%}

{% load static %}


{% block content %}
<main class="container mt-2">
    <div class="row">
      <section class="col vh-100">
        <div class="d-flex align-items-center gap-2 mb-4 mt-2 section-title">
            <h1>Log In</h1> 
        </div>

        <articles class="d-flex gap-3 flex-column">
        <div class="container">
            <div class="login-container">
                <form id="loginForm" action="/login/" method ="post" novalidate>
                    {% csrf_token %}
                   
                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                            <label for="id_username" class="col-form-label section-title ml-0 mb-3">Username</label>
                        </div>
                        <div class="col-auto">
                        {{ form.username }}
                        {{ form.username.errors }}
                        </div>
                    </div>
                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                            <label for="id_password" class="col-form-label section-title mt-3 mb-3">Password</label>
                        </div>
                        <div class="col-auto">
                        {{ form.password }}
                        {{ form.password.errors }}
                        </div>
                    </div>
                
                    <button type="submit" class="btn btn-outline-success btn-block mt-4 mb-4">Login</button>
                
                    <div class="mt-2">
                        <a class="d-block link-offset-2 link-underline-opacity-100-hover" href="{% url 'signup' %}">create new account</a>
                    </div>
                </form>
                {% if form.non_field_errors %}
                <div class="alert alert-danger mt-3">
                {{ form.non_field_errors }}
                </div>
                {% endif %}
            </div>
        </div>
    </articles>
</section>
</div>
</main>

{% endblock %}

app/templates/new_question.html
{% extends "layouts/base.html"%}

{% load static %}


{% block content %}
<div class="row">
    <section class="col">
        <div class="d-flex align-items-center gap-2 mb-4">
            <h1 class="section-title">New Questions</h1>
        </div>
        <article id="myForm" class="d-flex gap-3 flex-column">
            <div class="row g-3 align-items-center">
                <div class="col-auto">
                    <label for="inputTitle" class="col-form-label section-title">Title</label>
                </div>
                <div class="col-auto">
                    <input type="text" id="inputTitle6" class="form-control" placeholder="How to build a moon park?" 
                    style="width: 300%;" maxlength="100" aria-describedby="TitleHelpInline">
                </div>
            </div>
            <p id="error-message" class="error" style="color: red; font-weight: bold;"></p>
        
            <div class="row g-3 align-items-center">
                <div class="col-auto">
                    <label for="inputText6" class="col-form-label section-title">Text</label>
                </div>
                <div class="col-auto">
                    <input type="text" id="inputText6" class="form-control" placeholder="Really, how? Have no idea about it" 
                    style="width: 300%; height: 300px;" maxlength="350" aria-describedby="TextHelpInline">
                </div>
            </div>
        
            <div class="row g-3 align-items-center">
                <div class="col-auto">
                    <label for="inputTags6" class="col-form-label section-title">Tags</label>
                </div>
                <div class="col-auto">
                    <input type="text" id="inputTags6" class="form-control" placeholder="moon, park, puzzle" 
                    style="width: 300%;" maxlength="150" aria-describedby="TagsHelpInline">
                </div>
            </div>
        
            <div class="d-grid gap-2 w-25">
                <button class="btn btn-outline-send" type="button" id="submitButton">ASK!</button>
            </div>
        </article>
    </section>
</div>
{% endblock %}

app/templates/settings.html
{% extends "layouts/base.html"%}

{% load static %}
{% block content %}
<div class="row">
    <section class="col vh-100">
        <div class="d-flex align-items-center gap-2 mb-4 mt-2 section-title">
            <h1>Settings: Mr. Ask</h1> 
        </div>

        <articles class="d-flex gap-3 flex-column">
        <div class="container">
            <div class="login-container">
                <form id="loginForm">
                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                            <label for="inputLogin6" class="col-form-label section-title m-4">Login</label>
                        </div>
                        <div class="col-auto">
                            <input type="text" id="inputLogin6" class="form-control" placeholder="Enter your login here" 
                             maxlength="25" aria-describedby="LoginHelpInline">
                        </div>
                    </div> 
                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                            <label for="inputEmail" class="col-form-label section-title m-4">Email </label>
                        </div>
                        <div class="col-auto">
                            <input type="text" id="inputEmail" class="form-control" placeholder="Enter your Email here" 
                             maxlength="25" aria-describedby="PasswordHelpInline">
                        </div>
                    </div> 
                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                            <label for="inputNickname6" class="col-form-label section-title m-1">NickName</label>
                        </div>
                        <div class="col-auto">
                            <input type="text" id="inputNickname6" class="form-control" placeholder="Enter your NickName" 
                             maxlength="25" aria-describedby="LoginHelpInline">
                        </div>
                    </div> 
                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                            <label for="formFile" class="col-form-label section-title m-3"><p>Upload<br>avatar</p></label>
                        </div>
                        <div class="col-auto">
                            <div class="mb-3">
                                <input class="form-control" type="file" id="formFile">
                            </div>
                        </div>
                    </div> 

                    <p id="error-message" class="error" style="color: red; font-weight: bold;"></p>
                
                    <button type="submit" class="btn btn-outline-success btn-block mt-4 mb-4">Save</button>
                </form>
                <script>
                    document.getElementById('loginForm').addEventListener('submit', function(event) {
                        event.preventDefault(); 
                
                        const login = document.getElementById('inputLogin6').value.trim();
                        const email = document.getElementById('inputEmail').value.trim();
                        const nickname = document.getElementById('inputNickname6').value.trim();
                        const errorMessage = document.getElementById('error-message');
                
                        const emailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/;
            
                        let errors = [];
                
                        if (login === '') {
                            errors.push('Login must contained symbols;');
                        }
                
                        if (!emailRegex.test(email)) {
                            errors.push('Enter correct email;');
                        }
                
                        if (nickname === '') {
                            errors.push('NickName must contained symbols;');
                        }
                
                        if (errors.length > 0) {
                            errorMessage.textContent = errors.join(' ');
                        } else {
                            errorMessage.textContent = '';
                            alert('Its OK');
                            // Для реальной отправки формы можно использовать:
                            // event.target.submit();
                        }
                    });
                </script>
            </div>
        </div>
        </articles>
    </section>
</div>
{% endblock %}

app/templates/signup.html
{% extends "layouts/base.html"%}

{% load static %}


{% block content %}
<main class="container mt-2">
    <div class="row">
      <section class="col vh-100">
        <div class="d-flex align-items-center gap-2 mb-4 mt-2 section-title">
            <h1>Registration</h1> 
        </div>

        <articles class="d-flex gap-3 flex-column">
        <div class="container">
            <div class="signup-container">
                <form id="registrationForm" action="{% url 'signup' %}" method ="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.non_field_errors }}

                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                            <label for="id_username" class="col-form-label section-title ml-0 mb-3">Username</label>
                        </div>
                        <div class="col-auto">
                        {{ form.username }}
                        {{ form.username.errors }}
                        </div>
                    </div>

                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                            <label for="id_email" class="col-form-label section-title m-3">Email</label>
                        </div>
                        <div class="col-auto">
                        {{ form.email }}
                        {{ form.email.errors }}
                        </div>
                    </div>

                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                            <label for="id_nickname" class="col-form-label section-title mb-3 mt-3">Nickname</label>
                        </div>
                        <div class="col-auto">
                        {{ form.nickname }}
                        {{ form.nickname.errors }}
                        </div>
                    </div>

                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                            <label for="id_avatar" class="col-form-label section-title m-2"><p>Upload<br>avatar</p></label>
                        </div>
                        <div class="col-auto">
                        {{ form.avatar }}
                        {{ form.avatar.errors }}
                        </div>
                    </div>

                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                            <label for="id_password" class="col-form-label section-title mt-3 mb-3">Password</label>
                        </div>
                        <div class="col-auto">
                        {{ form.password }}
                        {{ form.password.errors }}
                        </div>
                    </div>

                    <div class="row g-3 align-items-center">
                        <div class="col-auto">
                            <label for="id_repeatpassword" class="col-form-label section-title"><p>Repeat <br>password</p</label>
                        </div>
                        <div class="col-auto">
                        {{ form.repeatpassword }}
                        {{ form.repeatpassword.errors }}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-outline-success btn-block mt-4 mb-4">Register</button>
                </form>
            </div>
        </div>
    </articles>

    </section>
</div>
</main>

{% endblock %}

app/templates/single_question.html
{% extends "layouts/base.html"%}
{% load static %}

{% block content %}
    
    {% include 'layouts/question.html' with question=question %}
    
    <hr class="my-4">
    <h2>Answers</h2>

    {% for answer in answers%}  
        {% include 'layouts/answer.html' with answer=answer %}
    {% endfor%}
    
    {% include 'layouts/pagination.html' %}

    <div class="row g-3 align-items-center">
        <div class="col-auto">
            <input type="Title" id="inputTitle6" class="form-control" placeholder="Enter your answer here" 
            style="width: 300%; height: 200px;" maxlength="350" aria-describedby="TitleHelpInline">
        </div>
    </div>
    <div class="d-grid gap-2 w-25 mb-3 mt-3">
        <button class="btn btn-outline-primary" type="button">Answer</button>
    </div>


{% endblock %}

        
    

app/templates/tag_questions.html
{% extends 'base.html' %}

{% block content %}
  <h2>Qiestions by tag: {{ tag.name }}</h2>
  
  {% for question in questions %}
    <div class="question">
      <h3><a href="{% url 'question' question.id %}">{{ question.name }}</a></h3>
      <p>{{ question.text|truncatechars:150 }}</p>
      <p><strong>Теги:</strong>
        {% for t in question.tag.all %}
          <a href="{% url 'questions_by_tag' t.name %}">#{{ t.name }}</a>{% if not forloop.last %}, {% endif %}
        {% endfor %}
      </p>
    </div>
  {% endfor %}

  {% include 'pagination.html' %}
{% endblock %}